<form name="singin" action="/<?=$this->getRequest()->url?>" method="post">
    <div class="input">
        <label>E-mail</label>
        <input name="email" type="email" />
    </div>
    <div class="input">
        <label>Password</label>
        <input name="password" type="password" />
    </div>
    <div class="submit">
        <input name="submit" type="submit" value="Sing in"/>
    </div>
</form>