<!DOCTYPE html>
<html>
    <head>
        <title>Minimal LAMP framework</title>
        <meta charset="utf-8">
        <link rel="stylesheet" href="/css/style.css" />
        <script src="/js/app.js"></script>
        <?php
            foreach ($this->scripts() as $type => $scripts) {
                foreach ($scripts as $script) {
                    if ($type == 'js') {
                        $tag = '<script src="/%s"></script>';
                    } else if ($type == 'css') {
                        $tag = '<link rel="stylesheet" href="/%s" />';
                    }
                    echo sprintf($tag, $script);
                }
            }
        ?>
    </head>
    <body>
        <div id="container">
            <?=$this->block('header')?>
            <?=$this->content?>
            <?=$this->block('footer')?>
        </div>
    </body>
</html>